name: LangChain4J CDI Build

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE'
      - 'NOTICE'
      - '*.md'
      - '.github/*.md'
      - '.github/*.yml'
      - '.github/*.conf'
      - '.github/ISSUE_TEMPLATE/*.md'
  pull_request:
    paths-ignore:
      - '.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE'
      - 'NOTICE'
      - '*.md'
      - '.github/*.md'
      - '.github/*.yml'
      - '.github/*.conf'
      - '.github/ISSUE_TEMPLATE/*.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: build with jdk 17

    steps:
      - uses: actions/checkout@v5
        name: checkout

      - uses: actions/setup-java@v4
        name: set up jdk 17
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
          cache-dependency-path: '**/pom.xml'

      - name: build with maven
        run: mvn -B formatter:validate verify --file pom.xml

  build-windows:
    runs-on: windows-latest
    name: build with jdk 17 on windows

    steps:
      - name: git configure long path
        run: git config --global core.longpaths true

      - uses: actions/checkout@v5
        name: checkout

      - uses: actions/setup-java@v4
        name: set up jdk 17
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
          cache-dependency-path: '**/pom.xml'

      - name: build with maven
        run: mvn -B formatter:validate verify --file pom.xml
